### ISSUE TITLE
Found a typo in the README.md

### ISSUE THREAD

**Issue by meenal21** [kcoder63/hacky#16]
**Description**

Hey @kcoder63, I was going through the description of the project Hacky and I found a typo in the README.md file in the repo. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13515337/111914882-e2861700-8a99-11eb-84dd-3cdbfe4d5ea4.png)

**Additional Context**    

Also, to maintain uniformity, you can capitalize all the first letters of Sentences in your list -
![image](https://user-images.githubusercontent.com/13515337/111914972-309b1a80-8a9a-11eb-8632-24f3c74c433f.png)

**Comment by meenal21** [comment]
I forgot one here - you can also replace help with helps here in the list
![image](https://user-images.githubusercontent.com/13515337/111915190-0564fb00-8a9b-11eb-94a6-238529d77caa.png)

**Comment by kcoder63** [comment]
Thank you for opening an issue! Will do the corrections or you can make a PR if you want

**Comment by meenal21** [comment]
Thanks, @kcoder63, I will raise a PR for this 👍
